#!/bin/bash

SYSTEM="$(uname -s)"
case "${SYSTEM}" in
    Linux*)    SYSTEM="LINUX";;
    Darwin*)   SYSTEM="MAC";;
    CYGWIN*)   SYSTEM="WINDOWS";;
    MINGW*)    SYSTEM="WINDOWS";;
    *)         SYSTEM="UNKNOWN";;
esac

echo "Building for ${SYSTEM}"
npx next build

if [ $SYSTEM == "LINUX" ]; then
    echo "Restarting NGINX"
    sudo cp nginx.conf /etc/nginx/sites-enabled/apteryx.xyz
    sudo systemctl restart nginx
else
    echo "Skipping NGINX setup"
fi
