#!/bin/bash

SYSTEM="$(uname -s)"
case "${SYSTEM}" in
    Linux*)     SYSTEM="LINUX";;
    Darwin*)    SYSTEM="MAC";;
    CYGWIN*)    SYSTEM="WINDOWS";;
    MINGW*)     SYSTEM="WINDOWS";;
esac

echo "Building for ${SYSTEM}"
blitz build

if [ $SYSTEM == "LINUX" ]; then
    echo "Restarting NGINX"
    sudo cp nginx.conf /etc/nginx/sites-enabled/apteryx.xyz
    sudo systemctl restart nginx
else
    echo "Skipping NGINX restart"
    echo "Generating sitemap and robots.txt"
    del public/site*.xml
    npx next-sitemap --config blitz.config.js
fi
