name: Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote commands
        uses: appleboy/ssh-action@master
        env:
          PROJECT_DIRECTORY: ${{ secrets.PROJECT_DIRECTORY }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: PROJECT_DIRECTORY
          script: |
            cd $PROJECT_DIRECTORY
            git pull
            npm run build
            npm run start
            echo "[Workflow] Deployed successfully"
